name: Website Build & Deploy

on:
  push:
    branches:
      - feature/ci-cd

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This project is built using hugo and outputs the result to the 'docs/' folder. 
        run: |
          make install
          hugo

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.